stages:
  - log-commits
  - build-graal
  - micronaut
  - test


#  _                                                 _ _
# | | ___   __ _        ___ ___  _ __ ___  _ __ ___ (_) |_ ___
# | |/ _ \ / _` |_____ / __/ _ \| '_ ` _ \| '_ ` _ \| | __/ __|
# | | (_) | (_| |_____| (_| (_) | | | | | | | | | | | | |_\__ \
# |_|\___/ \__, |      \___\___/|_| |_| |_|_| |_| |_|_|\__|___/
#          |___/
log-commits:
  image: alpine:3.8
  stage: log-commits
  script:
    - ./log-commits.sh


#  _           _ _     _                             _
# | |__  _   _(_) | __| |       __ _ _ __ __ _  __ _| |
# | '_ \| | | | | |/ _` |_____ / _` | '__/ _` |/ _` | |
# | |_) | |_| | | | (_| |_____| (_| | | | (_| | (_| | |
# |_.__/ \__,_|_|_|\__,_|      \__, |_|  \__,_|\__,_|_|
#                              |___/
build-graal:
  stage: build-graal
  cache:
    key: ${GRAAL_LAST_COMMIT}
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
      - $CI_PROJECT_DIR/graal/openjdk1.8.0_222-jvmci-19.3-b02
  artifacts:
    expire_in: 5 days
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
      - $CI_PROJECT_DIR/graal/openjdk1.8.0_222-jvmci-19.3-b02
  script:
    - if [ -d $CI_PROJECT_DIR/graal ]; then exit 0; fi
    - ./build-graal.sh


#            _                                  _
#  _ __ ___ (_) ___ _ __ ___  _ __   __ _ _   _| |_
# | '_ ` _ \| |/ __| '__/ _ \| '_ \ / _` | | | | __|
# | | | | | | | (__| | | (_) | | | | (_| | |_| | |_
# |_| |_| |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
#
.micronaut:build-template: &micronaut-build-template
  stage: micronaut
  artifacts:
    expire_in: 5 days
  allow_failure: true
  retry:
    max: 2
    when:
      - runner_system_failure

micronaut:build-basic-app:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-basic-app/basic-app
  script:
    - ./build-micronaut-basic-app.sh

micronaut:build-consul-http-client:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-service-discovery-consul-http-client/service-discovery
  script:
    - ./build-micronaut-consul-http-client.sh

micronaut:build-zipkin-graal:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-zipkin-graal/zipkin-graal
  script:
    - ./build-micronaut-zipkin-graal.sh

micronaut:build-function-graal:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-function-graal/function-graal
  allow_failure: true
  script:
    - ./build-micronaut-function-graal.sh

micronaut:build-rabbitmq-graal:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-rabbitmq-graal/graal-rabbitmq
  allow_failure: true
  script:
    - ./build-micronaut-rabbitmq-graal.sh

micronaut:build-management-graal:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-management-graal/management-graal
  allow_failure: true
  script:
    - ./build-micronaut-management-graal.sh

micronaut:build-views-graal-freemarker:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-views-graal/views-graal-freemarker
  allow_failure: true
  script:
    - ./build-micronaut-views-graal.sh freemarker

micronaut:build-views-graal-handlebars:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-views-graal/views-graal-handlebars
  allow_failure: true
  script:
    - ./build-micronaut-views-graal.sh handlebars

micronaut:build-views-graal-thymeleaf:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-views-graal/views-graal-thymeleaf
  allow_failure: true
  script:
    - ./build-micronaut-views-graal.sh thymeleaf

micronaut:build-views-graal-velocity:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-views-graal/views-graal-velocity
  allow_failure: true
  script:
    - ./build-micronaut-views-graal.sh velocity

micronaut:build-security-jwt-graal:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-security-jwt-graal/security-jwt-graal
  allow_failure: true
  script:
    - ./build-micronaut-security-jwt-graal.sh

micronaut:build-micronaut-data-jdbc-graal:
  <<: *micronaut-build-template
  artifacts:
    paths:
      - $CI_PROJECT_DIR/micronaut-data-jdbc-graal/mn-data-jdbc-graal
  allow_failure: true
  script:
    - ./build-micronaut-data-jdbc-graal.sh


#  _            _
# | |_ ___  ___| |_
# | __/ _ \/ __| __|
# | ||  __/\__ \ |_
#  \__\___||___/\__|
#
.micronaut:test-template: &micronaut-test-template
  stage: test
  image: frolvlad/alpine-glibc

micronaut:test-basic-app:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-basic-app
  script:
    - ./test-basic-app.sh

micronaut:test-consul-http-client:
  <<: *micronaut-test-template
  services:
    - name: consul:1.4.0
      alias: consulhost
  dependencies:
    - micronaut:build-consul-http-client
  script:
    - ./test-consul-http-client.sh

micronaut:test-zipkin-graal:
  <<: *micronaut-test-template
  services:
    - name: openzipkin/zipkin:2.11.12
      alias: openzipkin
  dependencies:
    - micronaut:build-zipkin-graal
  script:
    - ./test-zipkin-graal.sh

micronaut:test-function-graal:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-function-graal
  script:
    - ./test-function-graal.sh

micronaut:test-rabbitmq-graal:
  <<: *micronaut-test-template
  services:
    - name: rabbitmq:3.7.11
      alias: rabbitmqhost
  dependencies:
    - micronaut:build-rabbitmq-graal
  script:
    - ./test-rabbitmq-graal.sh

micronaut:test-management-graal:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-management-graal
  script:
    - ./test-management-graal.sh

micronaut:test-views-graal-freemarker:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-views-graal-freemarker
  script:
    - ./test-views-graal-freemarker.sh

micronaut:test-views-graal-handlebars:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-views-graal-handlebars
  script:
    - ./test-views-graal-handlebars.sh

micronaut:test-views-graal-thymeleaf:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-views-graal-thymeleaf
  script:
    - ./test-views-graal-thymeleaf.sh

micronaut:test-views-graal-velocity:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-views-graal-velocity
  script:
    - ./test-views-graal-velocity.sh

micronaut:test-security-jwt-graal:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-security-jwt-graal
  script:
    - ./test-security-jwt-graal.sh

micronaut:test-micronaut-data-jdbc-graal:
  <<: *micronaut-test-template
  dependencies:
    - micronaut:build-micronaut-data-jdbc-graal
  script:
    - ./test-micronaut-data-jdbc-graal.sh
