stages:
  - check
  - build
  - test


check-graal-repo:
  stage: check
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/.trigger_build
  script:
    - apt update && apt install -y jq
    - ./should-trigger-the-build.sh


build-graal:
  stage: build
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - ./build-graal.sh


micronaut-test-graal-experiments:
  stage: test
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - apt update && apt install -y openjdk-8-jdk
    - ./build-micronaut-graal-experiments.sh
