stages:
  - check
  - build

check-graal-repo:
  stage: check
#  artifacts:
#    expire_in: 1 hour
#    paths:
#      - $CI_PROJECT_DIR/.trigger_build
  script:
    - apt update && apt install -y jq
    - jq --version

build-graal:
  stage: build
  script:
    - echo "Building Graal..."


build-micronaut:
  stage: build
  script:
    - echo "Building Micronaut..."
