stages:
  - log-commits
  - build-graal
  - micronaut
  - test

log-commits:
  image: alpine:3.8
  stage: log-commits
  script:
    - ./log-commits.sh


build-graal:
  stage: build-graal
  cache:
    key: all
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
      - $CI_PROJECT_DIR/graal/openjdk1.8.0_192-jvmci-0.53
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
      - $CI_PROJECT_DIR/graal/openjdk1.8.0_192-jvmci-0.53
  script:
    - if [ -d graal/graal ]; then exit 0; fi
    - ./build-graal.sh


micronaut:build-graal-experiments:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal/fresh-graal
  allow_failure: true
  script:
    - ./build-micronaut-graal-experiments.sh

micronaut:build-basic-app:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-basic-app/basic-app
  allow_failure: true
  script:
    - ./build-micronaut-basic-app.sh

micronaut:build-consul-http-client:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-service-discovery-consul-http-client/service-discovery
  allow_failure: true
  script:
    - ./build-micronaut-consul-http-client.sh


micronaut:test-graal-experiments:
  stage: test
  dependencies:
    - micronaut:build-graal-experiments
  script:
    - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal/fresh-graal &
    - echo $! > mn_graal.pid
    - sleep 3
    - RESPONSE=$(curl localhost:8080)
    - EXPECTED_RESPONSE='{"_links":{"self":{"href":"/","templated":false}},"message":"Page Not Found"}'
    - EXIT_STATUS=0
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then EXIT_STATUS=1; fi
    - kill -9 `cat ./mn_graal.pid`
    - exit $EXIT_STATUS

micronaut:test-basic-app:
  stage: test
  dependencies:
    - micronaut:build-basic-app
  script:
    - $CI_PROJECT_DIR/micronaut-basic-app/basic-app &
    - echo $! > mn_graal.pid
    - sleep 3
    - RESPONSE=$(curl localhost:8080/hello/Micronaut)
    - EXPECTED_RESPONSE='{"msg":"Hello Micronaut"}'
    - EXIT_STATUS=0
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then EXIT_STATUS=1; fi
    - kill -9 `cat ./mn_graal.pid`
    - exit $EXIT_STATUS

micronaut:test-consul-http-client:
  stage: test
  services:
    - name: consul:1.4.0
      alias: consulhost
  dependencies:
    - micronaut:build-consul-http-client
  script:
    - MICRONAUT_CONFIG_FILES=$CI_PROJECT_DIR/application-consul-http-client.yml $CI_PROJECT_DIR/micronaut-service-discovery-consul-http-client/service-discovery &
    - echo $! > mn_graal.pid
    - sleep 3
    - RESPONSE=$(curl localhost:8080/api/hello/Micronaut)
    - EXPECTED_RESPONSE='Hello Micronaut'
    - EXIT_STATUS=0
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then EXIT_STATUS=1; fi
    - kill -9 `cat ./mn_graal.pid`
    - exit $EXIT_STATUS
