stages:
  - check
  - build

check-graal-repo:
  stage: check
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/.trigger_build
  script:
    - apt update && apt install -y jq
    - jq --version
    - ./should-trigger-the-build.sh

build-graal:
  stage: build
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - echo "Building Graal..."

build-micronaut:
  stage: build
  image: openjdk:8u191-jdk-alpine
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - echo "Building Micronaut..."
