stages:
  - log-commits
  - build-graal
  - micronaut
  - test

#  _                                                 _ _
# | | ___   __ _        ___ ___  _ __ ___  _ __ ___ (_) |_ ___
# | |/ _ \ / _` |_____ / __/ _ \| '_ ` _ \| '_ ` _ \| | __/ __|
# | | (_) | (_| |_____| (_| (_) | | | | | | | | | | | | |_\__ \
# |_|\___/ \__, |      \___\___/|_| |_| |_|_| |_| |_|_|\__|___/
#          |___/
log-commits:
  image: alpine:3.8
  stage: log-commits
  script:
    - ./log-commits.sh


#  _           _ _     _                             _
# | |__  _   _(_) | __| |       __ _ _ __ __ _  __ _| |
# | '_ \| | | | | |/ _` |_____ / _` | '__/ _` |/ _` | |
# | |_) | |_| | | | (_| |_____| (_| | | | (_| | (_| | |
# |_.__/ \__,_|_|_|\__,_|      \__, |_|  \__,_|\__,_|_|
#                              |___/
build-graal:
  stage: build-graal
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
      - $CI_PROJECT_DIR/graal/openjdk1.8.0_192-jvmci-0.54
  script:
    - ./build-graal.sh


#            _                                  _
#  _ __ ___ (_) ___ _ __ ___  _ __   __ _ _   _| |_
# | '_ ` _ \| |/ __| '__/ _ \| '_ \ / _` | | | | __|
# | | | | | | | (__| | | (_) | | | | (_| | |_| | |_
# |_| |_| |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
#
micronaut:build-graal-experiments:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal/fresh-graal
  allow_failure: true
  script:
    - ./build-micronaut-graal-experiments.sh

micronaut:build-basic-app:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-basic-app/basic-app
  allow_failure: true
  script:
    - ./build-micronaut-basic-app.sh

micronaut:build-consul-http-client:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-service-discovery-consul-http-client/service-discovery
  allow_failure: true
  script:
    - ./build-micronaut-consul-http-client.sh

micronaut:build-zipkin-graal:
  stage: micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-zipkin-graal/zipkin-graal
  allow_failure: true
  script:
    - ./build-micronaut-zipkin-graal.sh


#  _            _
# | |_ ___  ___| |_
# | __/ _ \/ __| __|
# | ||  __/\__ \ |_
#  \__\___||___/\__|
#
micronaut:test-graal-experiments:
  stage: test
  dependencies:
    - micronaut:build-graal-experiments
  script:
    - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal/fresh-graal &
    - sleep 3
    - RESPONSE=$(curl localhost:8080)
    - EXPECTED_RESPONSE='{"_links":{"self":{"href":"/","templated":false}},"message":"Page Not Found"}'
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then echo $RESPONSE && exit 1; fi
    - exit $EXIT_STATUS

micronaut:test-basic-app:
  stage: test
  dependencies:
    - micronaut:build-basic-app
  script:
    - $CI_PROJECT_DIR/micronaut-basic-app/basic-app &
    - sleep 3
    - RESPONSE=$(curl localhost:8080/hello/Micronaut)
    - EXPECTED_RESPONSE='{"msg":"Hello Micronaut"}'
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then echo $RESPONSE && exit 1; fi
    - exit $EXIT_STATUS

micronaut:test-consul-http-client:
  stage: test
  services:
    - name: consul:1.4.0
      alias: consulhost
  dependencies:
    - micronaut:build-consul-http-client
  script:
    - MICRONAUT_CONFIG_FILES=$CI_PROJECT_DIR/application-consul-http-client.yml $CI_PROJECT_DIR/micronaut-service-discovery-consul-http-client/service-discovery &
    - sleep 3
    - RESPONSE=$(curl localhost:8080/api/hello/Micronaut)
    - EXPECTED_RESPONSE='Hello Micronaut'
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then echo $RESPONSE && exit 1; fi
    - exit $EXIT_STATUS

micronaut:test-zipkin-graal:
  stage: test
  services:
    - name: openzipkin/zipkin:2.11.12
      alias: openzipkin
  dependencies:
    - micronaut:build-zipkin-graal
  script:
    - MICRONAUT_CONFIG_FILES=$CI_PROJECT_DIR/application-micronaut-zipkin-graal.yml $CI_PROJECT_DIR/micronaut-zipkin-graal/zipkin-graal &
    - sleep 3
    - curl localhost:8080/config
    - curl http://openzipkin:9411/zipkin/api/v2/services
    - curl http://openzipkin:9411/zipkin/api/v2/spans?serviceName=zipkin-graal
    - RESPONSE=$(curl localhost:8080/hello/Micronaut)
    - EXPECTED_RESPONSE='Hello Micronaut'
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then echo $RESPONSE && exit 1; fi
