stages:
  - check
  - build

check-graal-repo:
  stage: check
#  artifacts:
#    expire_in: 1 hour
#    paths:
#      - $CI_PROJECT_DIR/.trigger_build
  script:
    - apt update && apt install -y jq
    - jq --version
    - ./should-trigger-the-build.sh

build-graal:
  stage: build
  script:
    - echo $SHOULD_RUN
    - echo "Building Graal..."
  only:
    variables:
      - $SHOULD_RUN


build-micronaut:
  stage: build
  script:
    - echo $SHOULD_RUN
    - echo "Building Micronaut..."
