stages:
  - check
  - build-graal
  - build-micronaut
  - test


check-graal-repo:
  stage: check
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/.trigger_build
  script:
    - apt update && apt install -y jq
    - ./should-trigger-the-build.sh


build-graal:
  stage: build-graal
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/graal/graal/vm
      - $CI_PROJECT_DIR/graal/openjdk1.8.0_192-jvmci-0.53
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - ./build-graal.sh


micronaut-build-graal-experiments:
  stage: build-micronaut
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal/fresh-graal
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - ./build-micronaut-graal-experiments.sh


micronaut-test-graal-experiments:
  stage: test
  script:
    - if [ ! -f .trigger_build ]; then exit 0; fi
    - $CI_PROJECT_DIR/micronaut-graal-experiments/fresh-graal/fresh-graal &
    - echo $! > mn_graal.pid
    - sleep 3
    - RESPONSE=$(curl localhost:8080)
    - EXPECTED_RESPONSE='{"_links":{"self":{"href":"/","templated":false}},"message":"Page Not Found"}'
    - EXIT_STATUS=0
    - if [ "$RESPONSE" != "$EXPECTED_RESPONSE" ]; then EXIT_STATUS=1; fi
    - kill -9 `cat ./mn_graal.pid`
    - exit $EXIT_STATUS
